---
- name: Converge
  hosts: all
  gather_facts: false
  become: true

  pre_tasks:
    - name: Update Cach on Debian
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

- name: Test Playbook Rund Server Config
  ansible.builtin.import_playbook: ../../run-server-config.yml
