- name: 4.1 Disable Password based login for users
  ansible.builtin.blockinfile:
    path: /etc/ssh/sshd_config.d/disable_passwd_auth.conf
    block: |
      PasswordAuthentication no
      ChallengeResponseAuthentication no
      PermitRootLogin no
    create: true
    mode: "0644"
    owner: root
    group: root
    validate: 'sshd -T -f %s'
  notify: Restart sshd

- name: 4.2 Ensure sshd process is started and after boot
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: true
