- name: Turn on IOMMU (PCI Passthrough) in cmdline
  ansible.builtin.lineinfile:
    path: /etc/kernel/cmdline
    regexp: '^root=ZFS=rpool/ROOT/pve-1 boot=zfs'
    line: 'root=ZFS=rpool/ROOT/pve-1 boot=zfs intel_iommu=on'
  notify: Refresh proxmox boot tool

- name: Add Modules to boot
  ansible.builtin.blockinfile:
    path: /etc/modules
    block: |
      vfio
      vfio_iommu_type1
      vfio_pci
      vfio_virqfd
  notify: Update initramfs
