## Please install first galaxy collection by running: ansible-galaxy collection install community.general
- name: 12.1 Configure Firewall - Allow all outgoing traffic
  community.general.ufw:
    direction: out
    rule: allow

- name: 12.3 Configure Firewall - Allow ssh traffic
  community.general.ufw:
    direction: in
    rule: allow
    name: OpenSSH

- name: 12.2 Configure Firewall - Deny all incomming traffic
  community.general.ufw:
    direction: in
    rule: deny

- name: 12.4 Enable Firewall
  community.general.ufw:
    state: enabled
