- name: Restart sshd
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: Restart chrony
  ansible.builtin.service:
    name: chrony
    state: restarted

- name: Restart fail2ban
  ansible.builtin.service:
    name: fail2ban
    state: restarted

- name: Reconfigure unattended upgrades
  ansible.builtin.command:
    cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
  register: my_output # <- Registers the command output.
  changed_when: my_output.rc != 0
