- name: configure ubuntu server post installation
# based on Tutorial from Techno Tim https://technotim.live/posts/fist-13-things-linux/
  hosts: "ubuntu"
  become: yes
  tasks:
  
  - name: 1 update the server
    apt:
        update_cache: yes
        upgrade: 'yes'

  - name: 2.1 install automated updates
  # manual steps for ubuntu https://help.ubuntu.com/community/AutomaticSecurityUpdates 
    ansible.builtin.apt:
        name: unattended-upgrades
        state: present
        update_cache: true

  - name: 2.2 Create unattended upgrades configuration file
  # from https://luisjohnstone.com/2023/10/ubuntu-unattended-updates-with-ansible.html
    ansible.builtin.blockinfile:
        path: /etc/apt/apt.conf.d/20auto-upgrades
        block: |
          APT::Periodic::Update-Package-Lists "1";
          APT::Periodic::Unattended-Upgrade "1";
        create: true
        mode: "0644"
        owner: root
        group: root
        marker: "// {mark} ANSIBLE MANAGED BLOCK - unattended_upgrades settings"
    register: unattanded_upgrades_config_set

  - name: 2.3 Disable automated reboots
    ansible.builtin.blockinfile:
        path: /etc/apt/apt.conf.d/50unattended-upgrades
        block: |
          Unattended-Upgrade::Automatic-Reboot "false";
        create: true
        mode: "0644"
        owner: root
        group: root
        marker: "// {mark} ANSIBLE MANAGED BLOCK - unattended_upgrades settings"
    register: unattanded_upgrades_settings_set

  - name: 2.4 Reconfigure dpkg 
    ansible.builtin.command:
       cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
    when:
      - unattanded_upgrades_config_set.changed or
        unattanded_upgrades_settings_set.changed

  - name: 3 Disable Login from root account
    ansible.builtin.command:
      cmd: sudo passwd -l root

  - name: 4.1 Disable Password based login for users
    ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config.d/disable_passwd_auth.conf
        block: |
          PasswordAuthentication no
          ChallengeResponseAuthentication no
        create: true
        mode: "0644"
        owner: root
        group: root
    register: sshd_settings_set

  - name: 4.2 Restart sshd process
    ansible.builtin.command:
      cmd: sudo systemctl restart sshd
    when:
      - sshd_settings_set.changed
  
# TASK 5 Configure Static IP Address in Cloud Init on Proxmox as well as on the Unifi DHCFP Server 

#  - name: 6.1 Install alternative Shell oh-my-zsh
#    ansible.builtin.command:
#      cmd: sudo apt-get install zsh -y

#  - name: 6.2 Install powerline fonts 
#    ansible.builtin.command:
#      cmd: sudo apt-get install powerline fonts-powerline -y

#  - name: 6.3 Download ohmyzsh install script 
#    ansible.builtin.command:
#      cmd: wget https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh

#  - name: 6.4 Install ohmyzsh by running install script 
#    ansible.builtin.command:
#      cmd: bash install.sh --unattended --keep-zshrc --skip-chsh

# Task 7 Check if enough space is available, otherwise increase harddisk size in Proxmox to e.g. 8GB
# Task 8 Hostname already set by CloudInit

  - name: 9 Set correct timezone Europe/Berlin
    ansible.builtin.command:
      cmd: sudo timedatectl set-timezone Europe/Berlin

# Task 10 Setup local NTP Server
# sudo nano /etc/systemd/timesyncd.conf
### NTP=192.168.0.4
# sudo timedatectl set-ntp off
# sudo timedatectl set-ntp on

  - name: 11 Install Qemu Guest Agent on Virtual Machines
    ansible.builtin.apt:
        name: qemu-guest-agent
        state: present
        update_cache: true
    become: yes

  
# Task 12 Configure Firewall
## Please install first galaxy collection by running: ansible-galaxy collection install community.general
  - name: 12.1 Configure Firewall - Allow all outgoing traffic
    community.general.ufw:
      direction: out
      rule: allow

  - name: 12.2 Configure Firewall - Deny all incomming traffic
    community.general.ufw:
      direction: in
      rule: deny
  
  - name: 12.3 Configure Firewall - Allow ssh traffic
    community.general.ufw:
      direction: in
      rule: allow
      name: OpenSSH
  
  - name: 12.4 Enable Firewall
    community.general.ufw:
      state: enabled

# Task 13 Install and Configure Fail2Ban
  - name: 13.1 Install Fail2Ban
    ansible.builtin.apt:
        name: fail2ban
        state: present
        update_cache: true
    become: yes

  - name: 13.2 Configure jail.conf as local file to survive updates
    ansible.builtin.command:
      cmd: sudo cp /etc/fail2ban/jail.conf /etc/fail2ban/jail.local

  - name: 13.3 Configure bantime in jail.local
    ansible.builtin.lineinfile:
        path: /etc/fail2ban/jail.local
        insertafter: '[DEFAULT]'
        firstmatch: true
        regexp: '^bantime\s*=\s*(.*)$'
        line: bantime = 1440m
    register: fail2ban_config_set

  - name: 13.4 Configure findtime in jail.local
    ansible.builtin.lineinfile:
        path: /etc/fail2ban/jail.local
        insertafter: '[DEFAULT]'
        firstmatch: true
        regexp: '^findtime\s*=\s*(.*)$'
        line: findtime = 60m
    register: fail2ban_config_set

  - name: 13.5 Configure maxretry in jail.local
    ansible.builtin.lineinfile:
        path: /etc/fail2ban/jail.local
        insertafter: '[DEFAULT]'
        firstmatch: true
        regexp: '^maxretry\s*=\s*(.*)$'
        line: maxretry = 3
    register: fail2ban_config_set

  - name: 13.6 Configure backend in jail.local
    ansible.builtin.lineinfile:
        path: /etc/fail2ban/jail.local
        insertafter: '[DEFAULT]'
        firstmatch: true
        regexp: '^backend\s*=\s*(.*)$'
        line: backend = systemd
    register: fail2ban_config_set  
    
  - name: 13.7 Restart Fail2Ban service
    ansible.builtin.command:
      cmd: systemctl restart fail2ban
    when:
      - fail2ban_config_set.changed